name: footwear
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider:
  firebase_core:
  firebase_auth:
  firebase_database:
  cloud_firestore:
  firebase_storage:
  shared_preferences:
  fluttertoast:
  lottie:
  flutter_native_splash:
  image_picker: ^1.0.4
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - animation/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf